### ISSUE TITLE
Re-run of Stage 2 (with existing cluster) fails 100% of the time because no ceph-disk 

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1466]
Stage 2 works fine the first time around, when there is no cluster. But the second time, it sees OSDs and tries to run `osd.report` which currently requires ceph-disk to work properly.

```
[15/15] Executing runner advise.osds...
         |_  osd.report(human=False)...
               in target192168000054.teuthology... fail
               in target192168000030.teuthology... fail
               in target192168000069.teuthology... fail
[15/15] Executing runner advise.osds... fail
Finished stage ceph.stage.2: succeeded=14/15 failed=1/15

Failures summary:
advise.osds (/srv/modules/runners/advise.py):
  Exception occurred in runner advise.osds: Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 387, in _low
      data['return'] = self.functions[fun](*args, **kwargs)
    File "/srv/modules/runners/advise.py", line 124, in osds
      unconfigured = _tidy('unconfigured', report)
    File "/srv/modules/runners/advise.py", line 159, in _tidy
      if report[minion][key]:
  TypeError: string indices must be integers
```

**Comment by dlosku** [comment]
Just updated my cluster with the newest packages and now I'm having the same issue. Any estimates about the fix?

**Comment by jschmid1** [comment]
> Just updated my cluster with the newest packages and now I'm having the same issue. Any estimates about the fix?

@dlosku you seem to be using the master branch, which is not considered stable. Please consider using a package of the v0.8.x line

**Comment by smithfarm** [comment]
@dlosku Which operating system are you using, and what exactly do you mean by "the newest packages"? Which packages, and which versions?

**Comment by dlosku** [comment]
> 
> 
> @dlosku Which operating system are you using, and what exactly do you mean by "the newest packages"? Which packages, and which versions?

Sorry, I'm using SLES 12 SP3 and SES 5.5 (CEPH 12.2.8+git.1536505967.080f2248ff-2.15.1), deesea is 0.8.7-2.24.1.

**Comment by dlosku** [comment]
> 
> 
> @dlosku That's odd. I wouldn't expect this bug to happen in that environment. Please run the following commands as root on your Salt Master node (admin node) and report back the output:
> 
> ```
> salt-run deepsea.version
> salt -I roles:storage osd.report
> ```
Hi,
```
Here:
storage-admin:~ # salt-run deepsea.version
0.8.7

storage-admin:~ # salt -I roles:storage osd.report
storage06:
    No OSD configured for
    /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000
storage04:
    No OSD configured for
    /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000
storage03:
    No OSD configured for
    /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000
storage01:
    No OSD configured for
    /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000
storage05:
    No OSD configured for
    /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000
storage02:
    No OSD configured for
    /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_03000000
```

**Comment by smithfarm** [comment]
@dlosku Could you also cut-and-paste here the exact error seen when you run Stage 2 (i.e. the same piece of the output that is in the description of this bug, but from your system)?

**Comment by dlosku** [comment]
Hi,
of course, here it is:
I pested the whole end of the stage, everything else runs thru fine except the last task:
```
[15/15]   advise.osds................................................ ❌ (0.4s)
            |_ osd.report(human=False) on
               storage02............................................. ❌ (0.1s)
               storage03............................................. ❌ (0.1s)
               storage01............................................. ❌ (0.1s)
               storage06............................................. ❌ (0.1s)
               storage04............................................. ❌ (0.1s)
               storage05............................................. ❌ (0.1s)

Ended stage: ceph.stage.2 succeeded=14/15 failed=1/15 time=81.5s

Failures summary:

advise.osds (/srv/modules/runners/advise.py):
  Exception occurred in runner advise.osds: Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
      data['return'] = self.functions[fun](*args, **kwargs)
    File "/srv/modules/runners/advise.py", line 118, in osds
      unconfigured = _tidy('unconfigured', report)
    File "/srv/modules/runners/advise.py", line 153, in _tidy
      if report[minion][key]:
  TypeError: string indices must be integers, not str
```
This is what deepsea.log contains:
```
2018-12-05 10:11:11,662 [INFO] deepsea.monitor: Started State step: [-1/15] name=osd.report(human=False) on=['storage02', 'storage03', 'storage01', 'storage06', 'storage04', 'storage05']
2018-12-05 10:11:11,695 [INFO] deepsea.monitor: Finished State step: [-1/15] name=osd.report(human=False) in=storage05 success=False
2018-12-05 10:11:11,697 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.686966',
          'cmd': '_return',
          'fun': 'osd.report',
          'fun_args': ['human=False'],
          'id': 'storage05',
          'jid': '20181205101111625251',
          'out': 'nested',
          'return': "ERROR executing 'osd.report': The following keyword arguments are not valid: human=False",
          'success': False},
 'tag': 'salt/job/20181205101111625251/ret/storage05'}
2018-12-05 10:11:11,697 [INFO] deepsea.monitor: Finished State step: [-1/15] name=osd.report(human=False) in=storage01 success=False
2018-12-05 10:11:11,699 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.690121',
          'cmd': '_return',
          'fun': 'osd.report',
          'fun_args': ['human=False'],
          'id': 'storage01',
          'jid': '20181205101111625251',
          'out': 'nested',
          'return': "ERROR executing 'osd.report': The following keyword arguments are not valid: human=False",
          'success': False},
 'tag': 'salt/job/20181205101111625251/ret/storage01'}
2018-12-05 10:11:11,699 [INFO] deepsea.monitor: Finished State step: [-1/15] name=osd.report(human=False) in=storage03 success=False
2018-12-05 10:11:11,702 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.689780',
          'cmd': '_return',
          'fun': 'osd.report',
          'fun_args': ['human=False'],
          'id': 'storage03',
          'jid': '20181205101111625251',
          'out': 'nested',
          'return': "ERROR executing 'osd.report': The following keyword arguments are not valid: human=False",
          'success': False},
 'tag': 'salt/job/20181205101111625251/ret/storage03'}
2018-12-05 10:11:11,704 [INFO] deepsea.monitor: Finished State step: [-1/15] name=osd.report(human=False) in=storage02 success=False
2018-12-05 10:11:11,709 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.695207',
          'cmd': '_return',
          'fun': 'osd.report',
          'fun_args': ['human=False'],
          'id': 'storage02',
          'jid': '20181205101111625251',
          'out': 'nested',
          'return': "ERROR executing 'osd.report': The following keyword arguments are not valid: human=False",
          'success': False},
 'tag': 'salt/job/20181205101111625251/ret/storage02'}
2018-12-05 10:11:11,709 [INFO] deepsea.monitor: Finished State step: [-1/15] name=osd.report(human=False) in=storage04 success=False
2018-12-05 10:11:11,712 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.694767',
          'cmd': '_return',
          'fun': 'osd.report',
          'fun_args': ['human=False'],
          'id': 'storage04',
          'jid': '20181205101111625251',
          'out': 'nested',
          'return': "ERROR executing 'osd.report': The following keyword arguments are not valid: human=False",
          'success': False},
 'tag': 'salt/job/20181205101111625251/ret/storage04'}
2018-12-05 10:11:11,714 [INFO] deepsea.monitor: Finished State step: [-1/15] name=osd.report(human=False) in=storage06 success=False
2018-12-05 10:11:11,715 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.706756',
          'cmd': '_return',
          'fun': 'osd.report',
          'fun_args': ['human=False'],
          'id': 'storage06',
          'jid': '20181205101111625251',
          'out': 'nested',
          'return': "ERROR executing 'osd.report': The following keyword arguments are not valid: human=False",
          'success': False},
 'tag': 'salt/job/20181205101111625251/ret/storage06'}
2018-12-05 10:11:11,830 [INFO] deepsea.monitor: Finished Runner step: [15/15] name=advise.osds() success=False
2018-12-05 10:11:11,835 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2018-12-05T08:11:11.812548',
          'fun': 'runner.advise.osds',
          'fun_args': [],
          'jid': '20181205101111039276',
          'return': 'Exception occurred in runner advise.osds: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/modules/runners/advise.py", line 118, in osds\n    unconfigured = _tidy(\'unconfigured\', report)\n  File "/srv/modules/runners/advise.py", line 153, in _tidy\n    if report[minion][key]:\nTypeError: string indices must be integers, not str\n',
          'success': False,
          'user': 'UNKNOWN'},
 'tag': 'salt/run/20181205101111039276/ret'}
2018-12-05 10:11:11,838 [INFO] deepsea.monitor: End stage: ceph.stage.2 jid=20181205100949093631 success=False
2018-12-05 10:11:13,027 [INFO] deepsea.monitor: Stopping the DeepSea event monitoring
```

**Comment by jschmid1** [comment]
That indeed does not look like a ceph-volume infused issue.. In that case I'd say that this is a genuine bug and might already be solved in the next release.. 
In the meanwhile you shouldn't worry as much, since this is just a reporting module which is not involved in the deployment itself.

Is your cluster in an expected state?

**Comment by dlosku** [comment]
> 
> 
> That indeed does not look like a ceph-volume infused issue.. In that case I'd say that this is a genuine bug and might already be solved in the next release..
> In the meanwhile you shouldn't worry as much, since this is just a reporting module which is not involved in the deployment itself.
> 
> Is your cluster in an expected state?

Yes, my cluster is fine! I'm just reconstructing rgw-role for a node and that requires run of stage.2. First I have to remove the role and then add it again. For a reason or other our S3 broke while we moved the nodes from dc to other. Can I run the stage regardless of the error?

**Comment by jschmid1** [comment]
> Yes, my cluster is fine! 

Good to hear!

> I'm just reconstructing rgw-role for a node and that requires run of stage.2. First I have to remove the role and then add it again. For a reason or other our S3 broke while we moved the nodes from dc to other. Can I run the stage regardless of the error?

I mean, sure this issue needs to be investigated, but if you don't have any other issues besides this since state, I would say it's safe to say that running other stages is fine.

Your previous comment (https://github.com/SUSE/DeepSea/issues/1466#issuecomment-444249448) tells that you have one disk that is not a OSD, yet. Is this correct/intended?

**Comment by jschmid1** [comment]
fixed

**Comment by sforsayeth** [comment]
Hi,

It looks like we're still seeing this issue despite updated packages from those mentioned in this thread. 

We're on:

- OS: SLES12-SP3
- SES 5.5: ceph-12.2.12+git.1557159481.20068e69f5-2.36.6.x86_64
- Deepsea: 0.8.12+git.0.e885d513e


I can't run stage 2 on an existing cluster:

```
[15/15]   advise.osds................................................ ❌ (288s)
            |_ osd.report(human=False) on
               en-r03n05.ceph.sut.................................... ✓ (6s)
               en-r01n01.ceph.sut.................................... ✓ (4s)
               en-r02n07.ceph.sut.................................... ❌ (0.6s)
               en-r02n06.ceph.sut.................................... ✓ (6s)
               en-r03n06.ceph.sut.................................... ✓ (6s)
               en-r03n07.ceph.sut.................................... ❌ (0.6s)
               en-r01n06.ceph.sut.................................... ❌ (0.3s)
               en-r03n02.ceph.sut.................................... ✓ (6s)
               en-r03n03.ceph.sut.................................... ❌ (0.6s)
               en-r01n02.ceph.sut.................................... ✓ (7s)
               en-r01n03.ceph.sut.................................... ✓ (288s)
               en-r03n04.ceph.sut.................................... ✓ (6s)
               en-r02n02.ceph.sut.................................... ✓ (4s)
               en-r03n01.ceph.sut.................................... ❌ (0.6s)
               en-r02n01.ceph.sut.................................... ✓ (4s)
               en-r01n07.ceph.sut.................................... ✓ (5s)
               en-r02n05.ceph.sut.................................... ✓ (6s)
               en-r02n04.ceph.sut.................................... ❌ (0.6s)
               en-r01n04.ceph.sut.................................... ❌ (0.2s)
               en-r01n05.ceph.sut.................................... ❌ (0.7s)
               en-r02n03.ceph.sut.................................... ❌ (0.2s)

Ended stage: ceph.stage.2 succeeded=14/15 failed=1/15 time=326.6s

Failures summary:

advise.osds (/srv/modules/runners/advise.py):
  Exception occurred in runner advise.osds: Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
      data['return'] = self.functions[fun](*args, **kwargs)
    File "/srv/modules/runners/advise.py", line 144, in osds
      unconfigured = _tidy('unconfigured', report)
    File "/srv/modules/runners/advise.py", line 179, in _tidy
      if report[minion][key]:
  TypeError: string indices must be integers, not str
```


Tail end of the log from `deepsea.log` on the admin node: 

```2019-10-04 11:53:23,755 [INFO] deepsea.monitor: Finished Runner step: [15/15] name=advise.osds() success=False
2019-10-04 11:53:23,757 [INFO] deepsea.monitor: State step error:
{'data': {'_stamp': '2019-10-04T01:53:23.747804',
          'fun': 'runner.advise.osds',
          'fun_args': [],
          'jid': '20191004114835040912',
          'return': 'Exception occurred in runner advise.osds: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/modules/runners/advise.py", line 144, in osds\n    unconfigured = _tidy(\'unconfigured\', report)\n  File "/srv/modules/runners/advise.py", line 179, in _tidy\n    if report[minion][key]:\nTypeError: string indices must be integers, not str\n',
          'success': False,
          'user': 'UNKNOWN'},
 'tag': 'salt/run/20191004114835040912/ret'}
2019-10-04 11:53:23,761 [INFO] deepsea.monitor: End stage: ceph.stage.2 jid=20191004114756586528 success=False
2019-10-04 11:53:24,874 [INFO] deepsea.monitor: Stopping the DeepSea event monitoring
```

Not all nodes appear to have cephdisk.list working correctly either. To take one node as an example: 


This works OK: `salt 'en-r02n07.ceph.sut' cephdisks.list`
This errors on some nodes: `salt -I roles:storage osd.report`:

(snipped just the portion relating to this node):
```en-r02n07.ceph.sut:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1455, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/var/cache/salt/minion/extmods/modules/osd.py", line 2390, in report
        un1, ch1 = _report_pillar(active)
      File "/var/cache/salt/minion/extmods/modules/osd.py", line 2455, in _report_pillar
        if not is_incorrect(readlink(osd)):
      File "/var/cache/salt/minion/extmods/modules/osd.py", line 2357, in is_incorrect
        config = OSDConfig(device)
      File "/var/cache/salt/minion/extmods/modules/osd.py", line 658, in __init__
        self.capacity = self.set_capacity()
      File "/var/cache/salt/minion/extmods/modules/osd.py", line 726, in set_capacity
        raise RuntimeError(error)
    RuntimeError: Mine on en-r02n07.ceph.sut for cephdisks.list```


Is it OK to re-open this ticket?

Cheers
